name: FastSurvival
main: com.biel.FastSurvival.FastSurvival
version: 3.9
load: STARTUP
#depend: [BKCommonLib]
api-version: 1.15
authors: [biels]
commands:
   save:
     description: Imperatively save the turrets data (should not need to be used). Deprecated.
     usage: /save
   load:
     description:  Imperatively laod the turrets data. Deprecated.
   maze:
     description: Test command.
   recall:
     description: Back to base!
     usage: Click items!
   b:
     description: Gives you all the special bows in FastSurvival
     aliases: [arcs, bows]
     usage: /b
   it:
     description: Gets all special items
     aliases: [items, specialitems]
   e:
     description: Gives you the standard equipment to fight as an established player
     aliases: [pilota]
   wand:
     description: Get a magic builder's wand
     aliases: [builder, w]
   moonmats:
     description: Gives you the items required to build a portal to the moon (creative).
   t:
     description: Turrets
     aliases: [turrets, torres]
   moon:
     description: Teleports you to the moon
     aliases: [lluna]
   sky:
     description: Teleports you to the sky
     aliases: [cel]